version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
    volumes:
      - .docker/mysql/data:/var/lib/mysql:delegated
      - .docker/mysql/mysqld.cnf:/etc/mysql/my.cnf:cached
    ports:
      - 3306:3306
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public_html:/var/www/html/public_html
  php:
    depends_on:
      - mysql
    build:
      context: ./.docker/php
      dockerfile: ./Dockerfile
    volumes:
      - ./.:/var/www/html
